config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations =>"registrations" ,:sessions =>"sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html\
root 'welcome#index'
resources :welcome
resources :home
resources :charges, only: [:new, :create]
resources :cards do
		member do
			get 'createcharge'
			end
		end
resources :orders do
  member do
    get 'cart'
     get 'showcart'
     get 'totalAmount'
  end
  
end

# resource :admin


namespace :admin do
	root '/admin/home#index'
	resources :users do 
		collection do
			get :signout
		end
	end
	resources :categories
	resources :subcategories
	resources :products


end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
has_many :products , dependent: :destroy
has_many :subcategory , dependent: :destroy
validates :name, presence: true,
length: { minimum: 5}

end

app/models/charge.rb
class Charge < ApplicationRecord
DEFAULT_CURRENCY = 'usd'.freeze
  def initialize(params, user)
    @@stripe_email = params[:stripeEmail]
    @stripe_token = params[:stripeToken]
    @order = params[:order_id]
    @user = user

  end

  def call(item_price)
    create_charge(find_customer,item_price)
  end

  private

  attr_accessor :user, :stripe_email, :stripe_token, :order

  def find_customer
  	begin
		  if stripe_token
		    retrieve_customer(stripe_token)
			byebug
		  else
		  	byebug
		    create_customer
		  end
	rescue 
  end
end
	  def retrieve_customer(stripe_token)
	    Stripe::Customer.retrieve(stripe_token) 
	  end

	  def create_customer
	    customer = Stripe::Customer.create(
	      email: stripe_email,
	      source: stripe_token
	    )
	    user.update(stripe_token: customer.id)
	    customer
	  end

	  def create_charge(customer,item_price)

	    Stripe::Charge.create(
	      customer: user.id,
	      amount: item_price,

	      description: customer.email,
	      currency: DEFAULT_CURRENCY
	    )
	  end

	
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_products
has_many :products, through: :order_products
belongs_to :user
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	has_many :order_products
	has_many :orders, through: :order_products
validates :name, presence: true,
length: { minimum: 5}


 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord

has_many :products , dependent: :destroy
belongs_to :category

validates :name, presence: true,
length: { minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :cards
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 after_create :assign_default_role



  def assign_default_role

    add_role(:user)
        # add_role(Role.find_by_name('user'))
  end


end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
	def index
		unless current_user.present? and current_user.has_role? :admin
			sign_out current_user
			redirect_to root_path
		end
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	def index
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index

	@cards = current_user.cards

	end

	def new
		@card = Card.new
		
	end

	def create
	
		@card_no = params[:card_no]
	    @stripe_token = params[:stripeToken]
	    @expiration_month = params[:expiration_month] 
	    @expiration_year = params[:expiration_year] 
		@user_id = current_user.id

		customer = Stripe::Customer.create(email: current_user.email, source: @stripe_token )
			# //params for entering into stripe account and in token id there is customer id generaed by stripe


		@expiry_month = customer.sources[:data][0][:exp_month]
		@expiry_year  = customer.sources[:data][0][:exp_year]
		@card_no_last = customer.sources[:data][0][:last4]

		@card = Card.new(user_id: @user_id, card_no: @card_no_last, expiration_year: @expiry_year, expiration_month: @expiry_month, Token: customer.id)
			if @card.save


			redirect_to cards_path

			 else
			
			 render 'index'
			end
	end
	def createcharge
		
		@card = Card.find(params[:id])
		@customer_id = @card.Token
		@order_id = session[:order_id]
		@order  = Order.find(@order_id)
		@total_price = @order.products.map(&:price).sum
		

		charge = Stripe::Charge.create(
    customer: @customer_id,
    amount: @total_price,
    
    currency: 'usd'

  )
		session[:order_id] = nil
		
		@order.update(status: "complete")

		
	end
	private
	 	def secure_params
	 		# not using it
	 	    params.require(:card).permit(:card_no, :token, :expiration_month ,:expiration_date ,:user_id)
		
		end
	
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

 rescue_from Stripe::CardError, with: :catch_exception
	def new
	@order = Order.find(session[:order_id])
	@Items_price = @order.products.map(&:price).sum
	
	end


	def create
	
	@order = Order.find(session[:order_id])
	@Items_price = @order.products.map(&:price).sum
  	Card.new(charges_params, current_user).call(@Items_price)
    redirect_to new_charge_path
	end
	private

  	def charges_params
    	params.permit(:stripeEmail, :stripeToken, :order_id)
  	end

  def catch_exception(exception)
    flash[:error] = exception.message
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
	@products = Product.all
	
	if session[:order_id].present?
		@current_order = Order.find(session[:order_id])
	else
	end
	
end

def show
	@product = Product.find(params[:id])
	@category = @product.category
	@subcategory = @product.subcategory
	
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

 	 def index

	 
	@order = Order.all

	# THIS IS FOR CART DISPLAY 
  	end

  	def create
  	end

  	def show
			# @Order_products = Product.find(params[:id])

	end

	def totalAmount
		
	@order = Order.find(params[:id])
	@Items_price = @order.products.map(&:price).sum
	end

	def showcart

		@order = Order.find(params[:id])
	end

  def cart
	   	@product = Product.find(params[:id])
  	unless session[:order_id].present?	
	  	@order = Order.new()
		@order.user_id = current_user.id
		@order.status  = 'incomplete'  	
	  	@order.save
	  	@order_products = @order.order_products.new()
	  	# check here 
	  	@order_products.product_id = @product.id
	  	@order_products.save
	    session[:order_id] = @order.id
	else
		@order = Order.find(session[:order_id])
		@order_products = @order.order_products.new()
	  	@order_products.product_id = @product.id
	  	@order_products.save
	end

 	 # @product = Product.find(params[:id])
 	# @name    =  @product.name
 	# @price   =  @product.price

 	

  	
  end

  def update
 

  end

  def destroy
  	
			@order_products = OrderProduct.find(params[:id])

		 	@order_products.destroy

			redirect_to home_index_path
		end

  # private
  # def order_products_params
  #   params.require(:order_item).permit(:quantity, :product_id)
  # end
   # private
	 #	def secure_params
	 # 	    	params.require(:orders).permit(:user_id, :status)
		# end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/home/index.html.erb
 
  <!-- <li><%= link_to 'add a new Category ', signout_admin_users_path%></li> -->
   <!-- <li><%= link_to 'Add a new subcategory ', signout_admin_users_path%></li> -->



   <div class="container-fluid">

                       
 
<div class="panel panel-default">
      
        
      </div>

      <div id="collapse2" class="panel-collapse collapse">
        
    </div>



            <div class="jumbotron" style="margin-top: -90px;">

            <div class="dropdown" style="float: right;">

    <button class="btn btn-success btn-circle dropdown-toggle" type="button" data-toggle="dropdown"><kbd >  Admin</kbd>
    <span class="caret"></span></button>
    <ul class="dropdown-menu">

      <li><%= link_to 'Sign out ', signout_admin_users_path%></li>
    
    </ul>
  </div>
</div>


                    
                 <div class="navbar-header">
                            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                                <i class="glyphicon glyphicon-align-left"></i>
                                <span>Get Started</span>
                            </button>
                        </div>

                
          </div>

                <br>

  
        <div  class="row well  well-sm">




       
            <!-- Sidebar Holder -->
            <nav id="sidebar">

                <div class="sidebar-header">
                    <h2><kbd>Shopify</kbd> </h2>
                </div>

                <ul class="list-unstyled components">
                  
                  <!--   <li class="active">
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">Home</a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li><a href="#">Home 1</a></li>
                            <li><a href="#">Home 2</a></li>
                            <li><a href="#">Home 3</a></li>
                        </ul>
                    </li> -->
                    <li>
                        <strong> <%= link_to 'Users  ', admin_users_path %></strong></li>
                        <li><strong> <%= link_to 'Products  ', admin_products_path %></strong></li></li>
                        <!-- <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"><strong>Category</a></strong> -->
                        <!-- <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li><a href="#">Page 1</a></li>
                            <li><a href="#">Page 2</a></li>
                            <li><a href="#">Page 3</a></li>
                        </ul> -->
                    </li>
                    <li>
                        <strong> <%= link_to 'Categories ', admin_categories_path %></strong></li>
                    </li>
                    <li>
                    <li><strong> <%= link_to 'Subcategories ', admin_subcategories_path%></strong></li>
                     </li>
                </ul>

                <ul class="list-unstyled CTAs">
                    <li><a href="#" class="download">Later Use</a></li>
                    <li><a href="#" class="article">Later Use</a></li>
                </ul>
            </nav>

         
                
                   
           <!-- jQuery CDN -->
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
         <!-- Bootstrap Js CDN -->
         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

         <script type="text/javascript">
             $(document).ready(function () {
                 $('#sidebarCollapse').on('click', function () {
                     $('#sidebar').toggleClass('active');
                 });
             });
         </script>
   

app/views/home/index.html.erb
<script language="javascript" type="text/javascript">
function clearText(field)
{
    if (field.defaultValue == field.value) field.value = '';
    else if (field.value == '') field.value = field.defaultValue;
}
</script>

<script type="text/javascript">

ddsmoothmenu.init({
  mainmenuid: "top_nav", //menu DIV id
  orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
  classname: 'ddsmoothmenu', //class added to menu's outer DIV
  //customtheme: ["#1c5a80", "#18374a"],
  contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>

<link rel="stylesheet" type="text/css" media="all" href="css/jquery.dualSlider.0.2.css" />


<script type="text/javascript">
    
    $(document).ready(function() {
        
        $(".carousel").dualSlider({
            auto:true,
            autoDelay: 6000,
            easingCarousel: "swing",
            easingDetails: "easeOutBack",
            durationCarousel: 1000,
            durationDetails: 600
        });
        
    });
    
</script>

</head>

<body>

<div id="templatemo_wrapper">
  <div id="templatemo_header" style="display: inline;">
    
      <div id="site_title">
          <h1><a href="#">Station Shop</a></h1>
        </div>
        
        <div id="header_right">
          <a href="#">My Account</a> | <a href="#">My Wishlist</a> | <a href="#">My Cart</a> | <a href="#">Checkout</a> | 

<% if current_user.present? %><%= link_to 'Sign out ', destroy_user_session_path , method: :delete%></button>
          <%else%>
          <%= link_to 'Sign In ', new_user_session_path%>
         <%end%>
    </div>
        
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_header -->
    
    <div id="templatemo_menu" style="background-color: black" >
     <nav class="navbar navbar-inverse" style="background-color: black">
      <div id="top_nav" class="ddsmoothmenu">
            <ul>
                <li><a href="index.html" class="selected">Home</a></li>
                <li><a href="products.html">Products</a>
                    <ul>
                        <li><a href="#submenu1">Sub menu 1</a></li>
                        <li><a href="#submenu2">Sub menu 2</a></li>
                        <li><a href="#submenu3">Sub menu 3</a></li>
                  </ul>
                </li>
                <li><a href="about.html">About</a>
                    <ul>
                        <li><a href="#submenu1">Sub menu 1</a></li>
                        <li><a href="#submenu2">Sub menu 2</a></li>
                        <li><a href="#submenu3">Sub menu 3</a></li>
                        <li><a href="#submenu4">Sub menu 4</a></li>
                        <li><a href="#submenu5">Sub menu 5</a></li>
                  </ul>
                </li>
                <li><a href="faqs.html">FAQs</a></li>
                <li><a href="checkout.html">Checkout</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
            <br style="clear: left" />
        </div> <!-- end of ddsmoothmenu -->
        </nav>
        <div id="menu_second_bar">
          <div id="top_shopping_cart">


          <% if @current_order.present? %>
          
                         <%= link_to 'Show Cart',showcart_order_path(@current_order.id) , class: 'btn btn-default'%>
              <%else%>
             
              <%end%>
            </div>
          <div id="templatemo_search">
                <form action="#" method="get">
                  <input type="text" value="Search" name="keyword" id="keyword" title="keyword" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field" />
                  <input type="submit" name="Search" value=" Search " alt="Search" id="searchbutton" title="Search" class="sub_btn"  />
                </form>
            </div>
            <div class="cleaner"></div>
      </div>
    </div> <!-- END of templatemo_menu -->
    
  
        </div><!-- /details_wrapper -->
        
   
  
      <div class="backgrounds">
        
       
        <div class="item item_3">
          <img src="/assets/01.jpg" alt="Slider 03" />
        </div><!-- /item -->
        
      </div><!-- /backgrounds -->
    </div> <!-- END of templatemo_middle -->
    
    <div id="templatemo_main">
      <div id="sidebar" class="float_l">
          <div class="sidebar_box" style="height: 100%;"><span class="bottom"></span>
              <h3>Categories</h3>   
                <div class="content"> 
                  <ul class="sidebar_list">
                      <li class="first"><a href="#">Aenean varius nulla</a></li>
                       
                        <li><a href="#">Vestibulum eleifend</a></li>
                        <li class="last"><a href="#">Velit mi rutrum diam</a></li>
                    </ul>
                </div>
            </div>
          
        </div>
        <div id="content" class="float_r" style="width: 80%">
          <h1>New Products</h1>

<% @products.each do |product| %>
   
            <div class="product_box">
              <a href="productdetail.html"><img src = <%= product.avatar.url(:thumb)%></a>
 
               <p><kbd><%= product.name %><kbd></p>
               <p>Price : <%= product.price %></p>

               
                
                <p><strong><%= link_to 'Add to cart ',cart_order_path(product.id) %></strong></p>
                

                 <td><%= link_to 'Details', home_path(product) %></td>
            </div>          
<%end%>
            





        </div> 
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_main -->
    
    <div id="templatemo_footer" style="width: 100%">
      <p>
      <a href="index.html">Home</a> | <a href="products.html">Products</a> | <a href="about.html">About</a> | <a href="faqs.html">FAQs</a> | <a href="checkout.html">Checkout</a> | <a href="contact.html">Contact</a>
    </p>

      Copyright © 2048 <a href="#">Your Company Name</a>
    </div> <!-- END of templatemo_footer -->
    
</div> <!-- END of templatemo_wrapper -->

app/views/home/show.html.erb
<h4>Product Description	</h4>


<div class="well well-sm" style="width: 30%" >
	<p>
	<li><i>Product Category<%= @category.name%></i></li>
	</p>
</div>

<div class="well well-sm" style="width: 30%;"  >
	<p>
	<li><i>Product Category<%= @subcategory.name%></i></li>
	</p>
</div>
<div class="well well-sm"  >
<p style="text-align: center;">This product is made in japan and very reliable and user This product is made in japan and very reliable and user This product is made in japan and very reliable and user This product is made in japan and very reliable and user This product is made in japan and very reliable and user This product is made in japan and very reliable and user This product is made in japan and very reliable and user This product is made in japan and very reliable and user friendly</p>
</div>