config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations =>"registrations" ,:sessions =>"sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html\
root 'welcome#index'
resources :welcome
resources :home
resources :charges, only: [:new, :create]
resources :cards do
		member do
			get 'createcharge'
			end
		end
resources :orders do
  member do
    get 'cart'
     get 'showcart'
     get 'totalAmount'
  end
  
end

# resource :admin


namespace :admin do
	root '/admin/home#index'
	resources :users do 
		collection do
			get :signout
		end
	end
	resources :categories
	resources :subcategories
	resources :products


end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
has_many :products , dependent: :destroy
has_many :subcategory , dependent: :destroy
validates :name, presence: true,
length: { minimum: 5}

end

app/models/charge.rb
class Charge < ApplicationRecord
DEFAULT_CURRENCY = 'usd'.freeze
  def initialize(params, user)
    @@stripe_email = params[:stripeEmail]
    @stripe_token = params[:stripeToken]
    @order = params[:order_id]
    @user = user

  end

  def call(item_price)
    create_charge(find_customer,item_price)
  end

  private

  attr_accessor :user, :stripe_email, :stripe_token, :order

  def find_customer
  	begin
		  if stripe_token
		    retrieve_customer(stripe_token)
			byebug
		  else
		  	byebug
		    create_customer
		  end
	rescue 
  end
end
	  def retrieve_customer(stripe_token)
	    Stripe::Customer.retrieve(stripe_token) 
	  end

	  def create_customer
	    customer = Stripe::Customer.create(
	      email: stripe_email,
	      source: stripe_token
	    )
	    user.update(stripe_token: customer.id)
	    customer
	  end

	  def create_charge(customer,item_price)

	    Stripe::Charge.create(
	      customer: user.id,
	      amount: item_price,

	      description: customer.email,
	      currency: DEFAULT_CURRENCY
	    )
	  end

	
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_products
has_many :products, through: :order_products
belongs_to :user
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	has_many :order_products
	has_many :orders, through: :order_products
validates :name, presence: true,
length: { minimum: 5}


 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord

has_many :products , dependent: :destroy
belongs_to :category

validates :name, presence: true,
length: { minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :cards
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 after_create :assign_default_role



  def assign_default_role

    add_role(:user)
        # add_role(Role.find_by_name('user'))
  end


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController


def index
	
	@categories = Category.all
end

def show

	@admin_category = Category.find(params[:id])
end

def new
	@admin_category = Category.new
end

def edit
  @admin_category = Category.find(params[:id])	
end

def create
@admin_category = Category.new(secure_params)
		if @admin_category.save
			redirect_to admin_categories_path
		else
			render 'new'
		end
end

def update

@admin_category = Category.find(params[:id])
	if @admin_category.update(secure_params)
		redirect_to admin_categories_path
	else
		render 'edit'
	end	
end

def destroy
	@admin_category = Category.find(params[:id])
	@admin_category.destroy
	
	redirect_to admin_root_path
	
end

	 private
	 	def secure_params
	 		
	 	    	params.require(:category).permit(:name)

			end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	def index
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index

	@cards = current_user.cards

	end

	def new
		@card = Card.new
		
	end

	def create
	
		@card_no = params[:card_no]
	    @stripe_token = params[:stripeToken]
	    @expiration_month = params[:expiration_month] 
	    @expiration_year = params[:expiration_year] 
		@user_id = current_user.id

		customer = Stripe::Customer.create(email: current_user.email, source: @stripe_token )
			# //params for entering into stripe account and in token id there is customer id generaed by stripe


		@expiry_month = customer.sources[:data][0][:exp_month]
		@expiry_year  = customer.sources[:data][0][:exp_year]
		@card_no_last = customer.sources[:data][0][:last4]

		@card = Card.new(user_id: @user_id, card_no: @card_no_last, expiration_year: @expiry_year, expiration_month: @expiry_month, Token: customer.id)
			if @card.save


			redirect_to cards_path

			 else
			
			 render 'index'
			end
	end
	def createcharge
		
		@card = Card.find(params[:id])
		@customer_id = @card.Token
		@order_id = session[:order_id]
		@order  = Order.find(@order_id)
		@total_price = @order.products.map(&:price).sum
		

		charge = Stripe::Charge.create(
    customer: @customer_id,
    amount: @total_price,
    
    currency: 'usd'

  )
		session[:order_id] = nil
		
		@order.update(status: "complete")

		
	end
	private
	 	def secure_params
	 		# not using it
	 	    params.require(:card).permit(:card_no, :token, :expiration_month ,:expiration_date ,:user_id)
		
		end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
	@products = Product.all
	
	if session[:order_id].present?
		@current_order = Order.find(session[:order_id])
	else
	end
	
end

def show
	@product = Product.find(params[:id])
	@category = @product.category
	@subcategory = @product.subcategory
	
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

 	 def index

	 
	@order = Order.all

	# THIS IS FOR CART DISPLAY 
  	end

  	def create
  	end

  	def show
			# @Order_products = Product.find(params[:id])

	end

	def totalAmount
		
	@order = Order.find(params[:id])
	@Items_price = @order.products.map(&:price).sum
	end

	def showcart

		@order = Order.find(params[:id])
	end

  def cart
	   	@product = Product.find(params[:id])
  	unless session[:order_id].present?	
	  	@order = Order.new()
		@order.user_id = current_user.id
		@order.status  = 'incomplete'  	
	  	@order.save
	  	@order_products = @order.order_products.new()
	  	# check here 
	  	@order_products.product_id = @product.id
	  	@order_products.save
	    session[:order_id] = @order.id
	else
		@order = Order.find(session[:order_id])
		@order_products = @order.order_products.new()
	  	@order_products.product_id = @product.id
	  	@order_products.save
	end

 	 # @product = Product.find(params[:id])
 	# @name    =  @product.name
 	# @price   =  @product.price

 	

  	
  end

  def update
 

  end

  def destroy
  	
			@order_products = OrderProduct.find(params[:id])

		 	@order_products.destroy

			redirect_to home_index_path
		end

  # private
  # def order_products_params
  #   params.require(:order_item).permit(:quantity, :product_id)
  # end
   # private
	 #	def secure_params
	 # 	    	params.require(:orders).permit(:user_id, :status)
		# end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/categories/edit.html.erb
 <div class="form-group">
<%= form_for [:admin, @admin_category] do |form| %>
 
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@admin_category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @admin_category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <kbd style="float: left;"><%= form.label :Name %></kbd><br>
    <br>
<div class="container-fluid" style="margin-right:  30%;margin-left: 10% ;margin-top: -55px;">
    <%= form.text_field :name ,class: 'form-control' %>
  </div>
  </p>
 
  
 
  <p>
  <br>
  <br>
    <%= form.submit  class: 'btn btn-info'%>
  </p>
 
<% end %>
</div>

app/views/admin/categories/index.html.erb
<div class="well">
<h1>All Categories </h1>
 
<kbd><%= link_to 'Add a new category', new_admin_category_path , class: 'button-info'%></kbd>

<table class="table table-striped">
  <tr>
    <th><h4>Name</h4></th>
    
     <th colspan="2"></th>
  </tr>
  
  <% @categories.each do |category| %>
    <tr>
      <td><h4><kbd><%= category.name %></kbd></h4></td>
   <p>
     <td><%= link_to 'Show', admin_category_path(category) %></td> <pre>   <pre>
      <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
      <td><%= link_to 'Destroy', admin_category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
</p>
    </tr>
  <% end %>
</table>
 						</div>

app/views/admin/categories/new.html.erb
 <div class="form-group">
<%= form_for [:admin, @admin_category] do |form| %>
 
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@admin_category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @admin_category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <kbd style="float: left;"><%= form.label :Name %></kbd><br>
    <br>
<div class="container-fluid" style="margin-right:  30%;margin-left: 10% ;margin-top: -55px;">
    <%= form.text_field :name ,class: 'form-control' %>
  </div>
  </p>
 
  
 
  <p>
  <br>
  <br>
    <%= form.submit  class: 'btn btn-info'%>
  </p>
 
<% end %>
</div>

app/views/admin/categories/show.html.erb
<p>
  <strong>Name:</strong>
 <kbd> <%= @admin_category.name %></kbd>
</p>
 

 
<strong><h2>Subcategory</h2></strong>
 

<kbd><%= link_to 'Back', admin_categories_path %></kbd>