config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations =>"registrations" ,:sessions =>"sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html\
root 'welcome#index'
resources :welcome
resources :home
resources :charges, only: [:new, :create]
resources :cards do
		member do
			get 'createcharge'
			end
		end
resources :orders do
  member do
    get 'cart'
     get 'showcart'
     get 'totalAmount'
  end
  
end

# resource :admin


namespace :admin do
	root '/admin/home#index'
	resources :users do 
		collection do
			get :signout
		end
	end
	resources :categories
	resources :subcategories
	resources :products


end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
has_many :products , dependent: :destroy
has_many :subcategory , dependent: :destroy
validates :name, presence: true,
length: { minimum: 5}

end

app/models/charge.rb
class Charge < ApplicationRecord
DEFAULT_CURRENCY = 'usd'.freeze
  def initialize(params, user)
    @@stripe_email = params[:stripeEmail]
    @stripe_token = params[:stripeToken]
    @order = params[:order_id]
    @user = user

  end

  def call(item_price)
    create_charge(find_customer,item_price)
  end

  private

  attr_accessor :user, :stripe_email, :stripe_token, :order

  def find_customer
  	begin
		  if stripe_token
		    retrieve_customer(stripe_token)
			byebug
		  else
		  	byebug
		    create_customer
		  end
	rescue 
  end
end
	  def retrieve_customer(stripe_token)
	    Stripe::Customer.retrieve(stripe_token) 
	  end

	  def create_customer
	    customer = Stripe::Customer.create(
	      email: stripe_email,
	      source: stripe_token
	    )
	    user.update(stripe_token: customer.id)
	    customer
	  end

	  def create_charge(customer,item_price)

	    Stripe::Charge.create(
	      customer: user.id,
	      amount: item_price,

	      description: customer.email,
	      currency: DEFAULT_CURRENCY
	    )
	  end

	
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_products
has_many :products, through: :order_products
belongs_to :user
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	has_many :order_products
	has_many :orders, through: :order_products
validates :name, presence: true,
length: { minimum: 5}


 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord

has_many :products , dependent: :destroy
belongs_to :category

validates :name, presence: true,
length: { minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :cards
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 after_create :assign_default_role



  def assign_default_role

    add_role(:user)
        # add_role(Role.find_by_name('user'))
  end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

	def index
	@products = Product.all
	end

	def show
	@admin_product = Product.find(params[:id])

	end

	def new

	@admin_product = Product.new

	end

	def edit
	@admin_product = Product.find(params[:id])
	end

	def create

	@admin_product = Product.new(secure_params)
	if @admin_product.save
	redirect_to admin_products_path
	else
	render 'new'
		end
  	end

	def update
	@admin_product = Product.find(params[:id])
		if @admin_product.update(secure_params)
			redirect_to admin_products_path
		else
			render 'edit'
		end
	end

	def destroy
		
		@admin_product = Product.find(params[:id])

		 @admin_product.destroy

			redirect_to admin_products_path

		
	end

	 private
	 	def secure_params
	 	    	params.require(:product).permit(:name, :price, :category_id ,:subcategory_id , :avatar)
		end

	
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	def index
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index

	@cards = current_user.cards

	end

	def new
		@card = Card.new
		
	end

	def create
	
		@card_no = params[:card_no]
	    @stripe_token = params[:stripeToken]
	    @expiration_month = params[:expiration_month] 
	    @expiration_year = params[:expiration_year] 
		@user_id = current_user.id

		customer = Stripe::Customer.create(email: current_user.email, source: @stripe_token )
			# //params for entering into stripe account and in token id there is customer id generaed by stripe


		@expiry_month = customer.sources[:data][0][:exp_month]
		@expiry_year  = customer.sources[:data][0][:exp_year]
		@card_no_last = customer.sources[:data][0][:last4]

		@card = Card.new(user_id: @user_id, card_no: @card_no_last, expiration_year: @expiry_year, expiration_month: @expiry_month, Token: customer.id)
			if @card.save


			redirect_to cards_path

			 else
			
			 render 'index'
			end
	end
	def createcharge
		
		@card = Card.find(params[:id])
		@customer_id = @card.Token
		@order_id = session[:order_id]
		@order  = Order.find(@order_id)
		@total_price = @order.products.map(&:price).sum
		

		charge = Stripe::Charge.create(
    customer: @customer_id,
    amount: @total_price,
    
    currency: 'usd'

  )
		session[:order_id] = nil
		
		@order.update(status: "complete")

		
	end
	private
	 	def secure_params
	 		# not using it
	 	    params.require(:card).permit(:card_no, :token, :expiration_month ,:expiration_date ,:user_id)
		
		end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
	@products = Product.all
	
	if session[:order_id].present?
		@current_order = Order.find(session[:order_id])
	else
	end
	
end

def show
	@product = Product.find(params[:id])
	@category = @product.category
	@subcategory = @product.subcategory
	
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

 	 def index

	 
	@order = Order.all

	# THIS IS FOR CART DISPLAY 
  	end

  	def create
  	end

  	def show
			# @Order_products = Product.find(params[:id])

	end

	def totalAmount
		
	@order = Order.find(params[:id])
	@Items_price = @order.products.map(&:price).sum
	end

	def showcart

		@order = Order.find(params[:id])
	end

  def cart
	   	@product = Product.find(params[:id])
  	unless session[:order_id].present?	
	  	@order = Order.new()
		@order.user_id = current_user.id
		@order.status  = 'incomplete'  	
	  	@order.save
	  	@order_products = @order.order_products.new()
	  	# check here 
	  	@order_products.product_id = @product.id
	  	@order_products.save
	    session[:order_id] = @order.id
	else
		@order = Order.find(session[:order_id])
		@order_products = @order.order_products.new()
	  	@order_products.product_id = @product.id
	  	@order_products.save
	end

 	 # @product = Product.find(params[:id])
 	# @name    =  @product.name
 	# @price   =  @product.price

 	

  	
  end

  def update
 

  end

  def destroy
  	
			@order_products = OrderProduct.find(params[:id])

		 	@order_products.destroy

			redirect_to home_index_path
		end

  # private
  # def order_products_params
  #   params.require(:order_item).permit(:quantity, :product_id)
  # end
   # private
	 #	def secure_params
	 # 	    	params.require(:orders).permit(:user_id, :status)
		# end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<%= form_for [:admin, @admin_product] do |form| %>
 
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@admin_product.errors.count, "error") %> prohibited
        this Product from being saved:
      </h2>
      <ul>
        <% @admin_product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<p>
  

    <h2><kbd><%= form.label :Select_Category  %></kbd></h2><br>

<%= form.select :category_id, options_for_select(Category.all.map {|ct| [ct.name, ct.id ]})  %>

</p>


<p>
  
  <%= form.label :Select_SubCategory  %><br>

<%= form.select :subcategory_id, options_for_select(Subcategory.all.map {|ct| [ct.name, ct.id ]})  %>





</p>


  <p>
   <kbd style="float: left;"><%= form.label :Name %></kbd><br>
   <br>
<div class="container-fluid" style="margin-right:  30%;margin-left: 10% ;margin-top: -55px;">
    <%= form.text_field :name ,class: 'form-control'%>
  </div>
  </p>
  <p>
    <kbd style="float: left;><%= form.label :Price %></kbd><br>
    <div class="container-fluid" style="margin-right:  30%;margin-left: 10% ;margin-top: -40px;">
    <%= form.text_field :price ,class: 'form-control' %>
  </kbd>
  </p>
 
  
 
  <p>
    <%= form.submit class: 'btn-info' %>
  </p>
 
<% end %>

app/views/admin/products/index.html.erb
<h1><kbd>All Products <kbd></h1>
 
<button type="button" class="btn-small btn-success"><h5><i><%= link_to 'Add a new Product', new_admin_product_path %></i></h5></button>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Price</th>
     <th colspan="2"></th>
  </tr>
  
  <% @products.each do |product| %>
    <tr>
      <td><h2><%= product.name %></h2></td>
      <td><h2><%= product.price %></h2></td>
      <td><h2><img src = <%= product.avatar.url(:thumb)%>><img>  </h2></td>

   	<td><%= link_to 'Show', admin_product_path(product) %></td>
     
      <td><%= link_to 'Destroy', admin_product_path(product),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>
 						

app/views/admin/products/new.html.erb
<%= form_for [:admin, @admin_product] do |form| %>
 
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@admin_product.errors.count, "error") %> prohibited
        this Product from being saved:
      </h2>
      <ul>
        <% @admin_product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<p>
  

    <h2><kbd><%= form.label :Select_Category  %></kbd></h2><br>

<%= form.select :category_id, options_for_select(Category.all.map {|ct| [ct.name, ct.id ]})  %>

</p>


<p>
  
  <%= form.label :Select_SubCategory  %><br>

<%= form.select :subcategory_id, options_for_select(Subcategory.all.map {|ct| [ct.name, ct.id ]})  %>





</p>


  <p>
   <kbd style="float: left;"><%= form.label :Name %></kbd><br>
   <br>
<div class="container-fluid" style="margin-right:  30%;margin-left: 10% ;margin-top: -55px;">
    <%= form.text_field :name ,class: 'form-control'%>
  </div>
  </p>
  <p>
    <kbd style="float: left;><%= form.label :Price %></kbd><br>
    <div class="container-fluid" style="margin-right:  30%;margin-left: 10% ;margin-top: -40px;">
    <%= form.text_field :price ,class: 'form-control' %>
  </kbd>
  </p>
 



 <%= form.file_field :avatar %>

   
  
 
  <p>
    <%= form.submit class: 'btn-info' %>
  </p>
 
<% end %>

app/views/admin/products/show.html.erb
<kbd><h2>Current Selected Product</h2></kbd>


<p>
  <h3><strong>Name:</strong></h3>
  <h5><%= @admin_product.name %></h5>
</p>
<div class ="well">

<br>
<br>

 
 <p>
  <kbd><strong>price:</strong></kbd>
  <%= @admin_product.price %>
</p>

<p>
 <kbd> <strong>category_Id:</strong></kbd>
  <%= @admin_product.category.name %>
</p>

<p>
  <kbd><strong>Subcategory_Id:</strong></kbd>
  <%= @admin_product.subcategory.name %>
</p>
 


<%= link_to 'Back', admin_products_path  %>
</div>