config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations =>"registrations" ,:sessions =>"sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html\
root 'welcome#index'
resources :welcome
resources :home
resources :charges, only: [:new, :create]
resources :cards do
		member do
			get 'createcharge'
			end
		end
resources :orders do
  member do
    get 'cart'
     get 'showcart'
     get 'totalAmount'
  end
  
end

# resource :admin


namespace :admin do
	root '/admin/home#index'
	resources :users do 
		collection do
			get :signout
		end
	end
	resources :categories
	resources :subcategories
	resources :products


end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
has_many :products , dependent: :destroy
has_many :subcategory , dependent: :destroy
validates :name, presence: true,
length: { minimum: 5}

end

app/models/charge.rb
class Charge < ApplicationRecord
DEFAULT_CURRENCY = 'usd'.freeze
  def initialize(params, user)
    @@stripe_email = params[:stripeEmail]
    @stripe_token = params[:stripeToken]
    @order = params[:order_id]
    @user = user

  end

  def call(item_price)
    create_charge(find_customer,item_price)
  end

  private

  attr_accessor :user, :stripe_email, :stripe_token, :order

  def find_customer
  	begin
		  if stripe_token
		    retrieve_customer(stripe_token)
			byebug
		  else
		  	byebug
		    create_customer
		  end
	rescue 
  end
end
	  def retrieve_customer(stripe_token)
	    Stripe::Customer.retrieve(stripe_token) 
	  end

	  def create_customer
	    customer = Stripe::Customer.create(
	      email: stripe_email,
	      source: stripe_token
	    )
	    user.update(stripe_token: customer.id)
	    customer
	  end

	  def create_charge(customer,item_price)

	    Stripe::Charge.create(
	      customer: user.id,
	      amount: item_price,

	      description: customer.email,
	      currency: DEFAULT_CURRENCY
	    )
	  end

	
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_products
has_many :products, through: :order_products
belongs_to :user
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
	has_many :order_products
	has_many :orders, through: :order_products
validates :name, presence: true,
length: { minimum: 5}


 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord

has_many :products , dependent: :destroy
belongs_to :category

validates :name, presence: true,
length: { minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :cards
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 after_create :assign_default_role



  def assign_default_role

    add_role(:user)
        # add_role(Role.find_by_name('user'))
  end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	def index
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index

	@cards = current_user.cards

	end

	def new
		@card = Card.new
		
	end

	def create
	
		@card_no = params[:card_no]
	    @stripe_token = params[:stripeToken]
	    @expiration_month = params[:expiration_month] 
	    @expiration_year = params[:expiration_year] 
		@user_id = current_user.id

		customer = Stripe::Customer.create(email: current_user.email, source: @stripe_token )
			# //params for entering into stripe account and in token id there is customer id generaed by stripe


		@expiry_month = customer.sources[:data][0][:exp_month]
		@expiry_year  = customer.sources[:data][0][:exp_year]
		@card_no_last = customer.sources[:data][0][:last4]

		@card = Card.new(user_id: @user_id, card_no: @card_no_last, expiration_year: @expiry_year, expiration_month: @expiry_month, Token: customer.id)
			if @card.save


			redirect_to cards_path

			 else
			
			 render 'index'
			end
	end
	def createcharge
		
		@card = Card.find(params[:id])
		@customer_id = @card.Token
		@order_id = session[:order_id]
		@order  = Order.find(@order_id)
		@total_price = @order.products.map(&:price).sum
		

		charge = Stripe::Charge.create(
    customer: @customer_id,
    amount: @total_price,
    
    currency: 'usd'

  )
		session[:order_id] = nil
		
		@order.update(status: "complete")

		
	end
	private
	 	def secure_params
	 		# not using it
	 	    params.require(:card).permit(:card_no, :token, :expiration_month ,:expiration_date ,:user_id)
		
		end
	
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

 rescue_from Stripe::CardError, with: :catch_exception
	def new
	@order = Order.find(session[:order_id])
	@Items_price = @order.products.map(&:price).sum
	
	end


	def create
	
	@order = Order.find(session[:order_id])
	@Items_price = @order.products.map(&:price).sum
  	Card.new(charges_params, current_user).call(@Items_price)
    redirect_to new_charge_path
	end
	private

  	def charges_params
    	params.permit(:stripeEmail, :stripeToken, :order_id)
  	end

  def catch_exception(exception)
    flash[:error] = exception.message
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
	@products = Product.all
	
	if session[:order_id].present?
		@current_order = Order.find(session[:order_id])
	else
	end
	
end

def show
	@product = Product.find(params[:id])
	@category = @product.category
	@subcategory = @product.subcategory
	
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

 	 def index

	 
	@order = Order.all

	# THIS IS FOR CART DISPLAY 
  	end

  	def create
  	end

  	def show
			# @Order_products = Product.find(params[:id])

	end

	def totalAmount
		
	@order = Order.find(params[:id])
	@Items_price = @order.products.map(&:price).sum
	end

	def showcart

		@order = Order.find(params[:id])
	end

  def cart
	   	@product = Product.find(params[:id])
  	unless session[:order_id].present?	
	  	@order = Order.new()
		@order.user_id = current_user.id
		@order.status  = 'incomplete'  	
	  	@order.save
	  	@order_products = @order.order_products.new()
	  	# check here 
	  	@order_products.product_id = @product.id
	  	@order_products.save
	    session[:order_id] = @order.id
	else
		@order = Order.find(session[:order_id])
		@order_products = @order.order_products.new()
	  	@order_products.product_id = @product.id
	  	@order_products.save
	end

 	 # @product = Product.find(params[:id])
 	# @name    =  @product.name
 	# @price   =  @product.price

 	

  	
  end

  def update
 

  end

  def destroy
  	
			@order_products = OrderProduct.find(params[:id])

		 	@order_products.destroy

			redirect_to home_index_path
		end

  # private
  # def order_products_params
  #   params.require(:order_item).permit(:quantity, :product_id)
  # end
   # private
	 #	def secure_params
	 # 	    	params.require(:orders).permit(:user_id, :status)
		# end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if current_user.present?
			if current_user.has_role? :user
			 	redirect_to home_index_path , notice:'User Signed In'
			 else
			 	redirect_to admin_root_path
			end
		else
			redirect_to new_user_session_path , notice: 'I am logged out '
		end
	end 
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/createcharge.html.erb
Charge Created !!!!!
	
	<%= link_to 'Back home_index',home_index_path , class: 'btn btn-success' %>

app/views/cards/index.html.erb
<div class="jumbotron">
<h1>List of Credit Cards <h1>



<table class="table table-striped">
  <tr>
    <th><p>Card_#</p></th>
    <th><p>Expiration_Date</p></th>
     <th colspan="2"></th>
  </tr>
  
  <% @cards.each do |card| %>
    <tr>
      <td><p><%= card.card_no %></p></td>
      <td><p><%= card.expiration_month %>/<%= card.expiration_year %></p></td>
      

   	<td><p><%= link_to 'Proceed', createcharge_card_path(card.id) %><p></td>
     
      
    </tr>
  <% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <%= link_to 'Select you Card',cards_path%>
  <br>
  
<article>
  <%if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <%end %>

  <br>
  <label class="amount">
  <span>Amount: $<%= @Items_price%></span>
  </label>
</article>
<!-- <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%#= Rails.configuration.stripe[:publishable_key] %>"
  data-description="A month's subscription"
  data-amount="<%= @Items_price  %>"
  data-locale="auto"></script> -->
<%end%>


<div class=".payment-errors"></div>
 
<%=form_tag cards_path, id: "stripe-form" do%>
    <div class="formset">
        <label>Card Number</label>
        <%= text_field_tag :card_no ,'', class: 'credit-number' %>
        <!-- <input type="text" size="20" autocomplete="off" class="credit-number" /> -->
         <span>  </span>
    
 
    
        <label>Security Code/CVC</label>
        <%= text_field_tag :security_code , '', class: 'credit-security'%>
        
    </div>
 
    <div class="formset">
        <label>Expiration Month</label>
       <%= text_field_tag :expiration_month , '',class: "card-expiry-month"%>
       
        <span>  </span>
         <label>Expiration Year</label>
        <%= text_field_tag :expiration_year , '', class: "card-expiry-year"%>
    </div>
 <%= submit_tag "submit", class: "btn btn-large btn-primary" %>
  <!-- <button type="submit" class="submit">Submit Payment</button> -->
<%end%>

<script type="text/javascript">
  Stripe.setPublishableKey('pk_test_yiTaJMyOgZod3dBvgTrfKqYy');

// Stripe.setSecretKey('sk_test_deruWoZIju79f1enpK4mqKig')
function stripeResponseHandler(status, response) {
  console.log('ddddd');
    if (response.error) {
        $(".payment-errors").text(response.error.message);
    } 
    else {
        var form$ = $("#stripe-form");
        var token = response['id'];
        form$.append("<input type='hidden' name='stripeToken' value='" + token + "'/>");
        form$.get(0).submit();
    }
}
 
$(document).ready(function() {
  $("#stripe-form").submit(function(event) {
    $('.submit').attr("disabled", "disabled");
 
    Stripe.createToken({
        number: $('.credit-number').val(),
        cvc: $('.credit-security').val(),
        // exp_year: $('.card-expiry-month').val() +'/' + $('.card-expiry-year').val()
        exp_month: $('.card-expiry-month').val(),
        exp_year:  $('.card-expiry-year').val()
    }, stripeResponseHandler);


 
    // prevent the form from submitting with the default action
    return false;
  });
});


</script>

app/views/orders/cart.html.erb
<div class="well " style="border: 5px solid grey">
 <button type="button"><strong><%= link_to ' Back', home_index_path , class: 'btn btn-warning'%></strong></button></p>
 <div class="well " style="border: 5px solid black">
<table class="table table-striped">

<tr>
    <th>Name</th>
    <th>Price</th>
     <th colspan="2"></th>
  </tr>
 <%= @order.status %>
 <%= @order_products.quantity%>
 
  	<%@order.order_products.each do |op|%>
  		<tr><td><%= op.product.name%></td>
  		<td><%= op.product.price%><td>
  		
  		

	 <td><%= link_to 'Destroy', order_path(op),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
</td>
	<%end%>


<!--   <%= @order.status%>



<%= @order_products.quantity%>
 -->

app/views/orders/showcart.html.erb
<div class="well " style="border: 5px solid grey">
 <p><strong><%= link_to ' Back', home_index_path , class: 'btn btn-warning'%></strong></</p>
 <p> <strong><%= link_to ' Cash My order', totalAmount_order_path , class: 'btn btn-success'%></strong></p>
   </p>
  

 <div class="well " style="border: 5px solid black">
<table class="table table-striped">

<tr>
    <th>Name</th>
    <th>Price</th>
     <th colspan="2"></th>
  </tr>
 

 	
 	<%= @order.status %>

  		<%@order.order_products.each do |op|%>
  		<tr><td><%= op.product.name%></td>
  		<td><%= op.product.price%><td>
  		 <td><%= link_to 'Destroy', order_path(op),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
</td>
  		
  		<% end %>

app/views/orders/totalAmount.html.erb
<h2>Total Amount </h2>

<p>You Total Payment is :<br><kbd>Rs:-<%= @Items_price%><kbd></p>



<%= link_to 'Select your payment method', new_charge_path ,class: 'btn btn-info'%>

<%= link_to 'Back To Show Cart',showcart_order_path(@order.id), class: 'btn btn-warning' %>